spring:
  profiles:
    active:
    - dog
    - EN
    - prod

calebe:
  username: YmlUser
  password: YmlPassword
  jdbcurl: YmlUrl

---

spring:
  profiles: prod
calebe:
  username: YmlProdUser
  password: YmlProdPassword
  jdbcurl: YmlProdUrl